### PR TITLE
Add the first Use Case

### PR DESCRIPTION
**Pull request by antonianemi**
[*] Creation of the folder Documentation.
[*] Move all the documents to that folder.

### CODE REVIEW

**Comment by arnoldmartinez** [comment]
it's added your commits Antonio

**Comment by antonianemi** [comment]
Hey arnold, it seems that you didnt merge my pull request instead you closed, i just reopened again so you can check it one more time, thanks in advance.

**Comment by arnoldmartinez** [comment]
Hi. Antonio it has been merged your commits into master branch

**Comment by antonianemi** [comment]
thank you so much Arnold, so I would like to know, what's going on with the front end, do you have some examples for that?

**Pull request merged**
